<a href="https://colab.research.google.com/github/YaswanthPothineni/test/blob/main/Text_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
path_to_file = '/content/E.M.Forster.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [4]:
print(text[:500])

Chapter I
The Bertolini


“The Signora had no business to do it,” said Miss Bartlett, “no
business at all. She promised us south rooms with a view close
together, instead of which here are north rooms, looking into a
courtyard, and a long way apart. Oh, Lucy!”

“And a Cockney, besides!” said Lucy, who had been further saddened by
the Signora’s unexpected accent. “It might be London.” She looked at
the two rows of English people who were sitting at the table; at the
row of white bottles of water 


**Unique Characters**

In [5]:
# The unique characters in the file
unique = sorted(set(text))
print(unique)
len(unique)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '£', 'à', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'ó', 'ö', 'ù', 'Œ', 'œ', '—', '‘', '’', '“', '”']


103

**Text** **Processing**

**Text Vectorization :
Knowing that a neural network cannot process raw string data, we must give each character a numerical value. Let's make two dictionaries that can translate from character to numeric index and vice versa.**

In [6]:
char_to_ind = {u:i for i, u in enumerate(unique)}

In [7]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 '*': 8,
 ',': 9,
 '-': 10,
 '.': 11,
 '0': 12,
 '1': 13,
 '2': 14,
 '3': 15,
 '4': 16,
 '5': 17,
 '6': 18,
 '7': 19,
 '8': 20,
 '9': 21,
 ':': 22,
 ';': 23,
 '=': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '£': 82,
 'à': 83,
 'â': 84,
 'ä': 85,
 'æ': 86,
 'ç': 87,
 'è': 88,
 'é': 89,
 'ê': 90,
 'ì': 91,
 'í': 92,
 'ó': 93,
 'ö': 94,
 'ù': 95,
 'Œ': 96,
 'œ': 97,
 '—': 98,
 '‘': 99,
 '’': 100

In [8]:
ind_to_char = np.array(unique) # Index to character

In [9]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '£', 'à', 'â', 'ä', 'æ', 'ç', 'è', 'é', 'ê',
       'ì', 'í', 'ó', 'ö', 'ù', 'Œ', 'œ', '—', '‘', '’', '“', '”'],
      dtype='<U1')

In [10]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [11]:
encoded_text

array([28, 63, 56, ...,  1,  1,  0])

We now have a mapping that we can use to switch between characters and numbers.


In [12]:
sample_data = text[:20]
sample_data

'Chapter I\nThe Bertol'

In [13]:
encoded_text[:20]

array([28, 63, 56, 71, 75, 60, 73,  1, 34,  0, 45, 63, 60,  1, 27, 60, 73,
       75, 70, 67])

**Creating Batches**

In general, our goal is to have the model predict the following character with the best probability given a historical series of characters. The length of the historical series is up to the user. A sequence that is too short leaves us with insufficient information (e.g., given the letter "a," what is the next character), whereas a sequence that is too long causes training to take too long and is likely to overfit to sequence characters that are irrelevant to characters further out. Although there is no ideal sequence length, you should take into account the text itself, the length of typical phrases, and a good understanding of the letters and words that are related to one another.


In [14]:
print(text[:500])

Chapter I
The Bertolini


“The Signora had no business to do it,” said Miss Bartlett, “no
business at all. She promised us south rooms with a view close
together, instead of which here are north rooms, looking into a
courtyard, and a long way apart. Oh, Lucy!”

“And a Cockney, besides!” said Lucy, who had been further saddened by
the Signora’s unexpected accent. “It might be London.” She looked at
the two rows of English people who were sitting at the table; at the
row of white bottles of water 


In [15]:
stanza_line= 'The Signora had no business to do it,” said Miss Bartlett, “no business at all. She promised us south rooms with a view close together, instead of which here are north rooms, looking into a courtyard, and a long way apart. Oh, Lucy'

In [16]:
len(stanza_line)

231

So, on an average we can take length of line as 200

Training

In [17]:
seq_len = 200

In [18]:
total_num_seq = len(text)//(seq_len+1)

In [19]:
total_num_seq

11857

These individual character requests are transformed into sequences we can input as a batch using the batch method. Because zero indexing is used, we use seq_len+1. What drop_remainder signifies is as follows:

(Optional) Drop remaining items. a tf.bool scalar tf.Tensor that indicates whether the previous batch should be eliminated if it contains less elements than batch_size; the default approach is to keep the larger batch.



In [20]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

for i in char_dataset.take(500):
     print(ind_to_char[i.numpy()])

C
h
a
p
t
e
r
 
I


T
h
e
 
B
e
r
t
o
l
i
n
i






“
T
h
e
 
S
i
g
n
o
r
a
 
h
a
d
 
n
o
 
b
u
s
i
n
e
s
s
 
t
o
 
d
o
 
i
t
,
”
 
s
a
i
d
 
M
i
s
s
 
B
a
r
t
l
e
t
t
,
 
“
n
o


b
u
s
i
n
e
s
s
 
a
t
 
a
l
l
.
 
S
h
e
 
p
r
o
m
i
s
e
d
 
u
s
 
s
o
u
t
h
 
r
o
o
m
s
 
w
i
t
h
 
a
 
v
i
e
w
 
c
l
o
s
e


t
o
g
e
t
h
e
r
,
 
i
n
s
t
e
a
d
 
o
f
 
w
h
i
c
h
 
h
e
r
e
 
a
r
e
 
n
o
r
t
h
 
r
o
o
m
s
,
 
l
o
o
k
i
n
g
 
i
n
t
o
 
a


c
o
u
r
t
y
a
r
d
,
 
a
n
d
 
a
 
l
o
n
g
 
w
a
y
 
a
p
a
r
t
.
 
O
h
,
 
L
u
c
y
!
”




“
A
n
d
 
a
 
C
o
c
k
n
e
y
,
 
b
e
s
i
d
e
s
!
”
 
s
a
i
d
 
L
u
c
y
,
 
w
h
o
 
h
a
d
 
b
e
e
n
 
f
u
r
t
h
e
r
 
s
a
d
d
e
n
e
d
 
b
y


t
h
e
 
S
i
g
n
o
r
a
’
s
 
u
n
e
x
p
e
c
t
e
d
 
a
c
c
e
n
t
.
 
“
I
t
 
m
i
g
h
t
 
b
e
 
L
o
n
d
o
n
.
”
 
S
h
e
 
l
o
o
k
e
d
 
a
t


t
h
e
 
t
w
o
 
r
o
w
s
 
o
f
 
E
n
g
l
i
s
h
 
p
e
o
p
l
e
 
w
h
o
 
w
e
r
e
 
s
i
t
t
i
n
g
 
a
t
 
t
h
e
 
t
a
b
l
e
;
 
a
t
 
t
h
e


r
o
w
 
o
f
 
w
h
i
t
e
 
b
o
t
t
l
e
s
 
o
f
 
w
a
t
e
r
 


In [21]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

We now have our sequences, and to produce our target text sequences, we will carry out the following procedures for each of them:

1) Take the input text flow.
2) Shift the input text sequence one step ahead before assigning the target text sequence.
3) Combine them into a tuple.


In [22]:
def create_seq_targets(seq):
    input_txt = seq[:-1]
    target_txt = seq[1:]
    return input_txt, target_txt

In [23]:
data = sequences.map(create_seq_targets)

In [24]:
for input_txt, target_txt in  data.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 28  63  56  71  75  60  73   1  34   0  45  63  60   1  27  60  73  75
  70  67  64  69  64   0   0   0 101  45  63  60   1  44  64  62  69  70
  73  56   1  63  56  59   1  69  70   1  57  76  74  64  69  60  74  74
   1  75  70   1  59  70   1  64  75   9 102   1  74  56  64  59   1  38
  64  74  74   1  27  56  73  75  67  60  75  75   9   1 101  69  70   0
  57  76  74  64  69  60  74  74   1  56  75   1  56  67  67  11   1  44
  63  60   1  71  73  70  68  64  74  60  59   1  76  74   1  74  70  76
  75  63   1  73  70  70  68  74   1  78  64  75  63   1  56   1  77  64
  60  78   1  58  67  70  74  60   0  75  70  62  60  75  63  60  73   9
   1  64  69  74  75  60  56  59   1  70  61   1  78  63  64  58  63   1
  63  60  73  60   1  56  73  60   1  69  70  73  75  63   1  73  70  70
  68  74]
Chapter I
The Bertolini


“The Signora had no business to do it,” said Miss Bartlett, “no
business at all. She promised us south rooms with a view close
together, instead of which here ar

**Generating training batches**

We want to shuffle these sequences into a random order so the model doesn't overfit to any one area of the text and can instead generate characters given any seed text. Now that we have the actual sequences, we will create the batches.


In [25]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = data.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [26]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 200), dtype=tf.int64, name=None), TensorSpec(shape=(128, 200), dtype=tf.int64, name=None))>

**Creating the Model**

With two LSTM layers and an initial embedding layer, our LSTM-based model will also have a few more properties. The DeepMoji, whose original source code can be accessed here, served as the inspiration for this model's architecture.

The input layer will be the embedding layer, which functions as a sort of lookup table that converts each character's numerical indices into a vector with a "embedding dim" number of dimensions. As you can expect, the training becomes more difficult as the embedding size increases. This concept is comparable to word2vec, which maps words to an n-dimensional space. Results that have been embedded before being fed directly into the LSTM are typically more realistic.


In [27]:
# Length of the vocabulary in chars
vocab_size = len(unique)

# The embedding dimension
embed_dim = 64

# Number of RNN units
rnn_neurons = 1026

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

**Setting up Loss Function**

We may import sparse categorical crossentropy from Keras to calculate our loss. Additionally, we'll set this to logits=True.


In [29]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [30]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [31]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [32]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           6592      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 103)          105781    
                                                                 
Total params: 3,473,549
Trainable params: 3,473,549
Non-trainable params: 0
_________________________________________________________________


**Training the model**

Before we invest too much time in training, let's make sure our model is happy with everything. To verify that the model now predicts random characters devoid of any training, let's pass in a batch.



In [34]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 200, 103)  <=== (batch_size, sequence_length, vocab_size)


In [35]:
example_batch_predictions

<tf.Tensor: shape=(128, 200, 103), dtype=float32, numpy=
array([[[-8.02959315e-04,  1.48999956e-04, -2.72493437e-03, ...,
          2.37293192e-03, -1.63633842e-03, -2.77730078e-03],
        [ 3.52706201e-03, -3.80177773e-03, -3.98030039e-03, ...,
         -1.37914467e-04, -3.49699170e-03, -6.56784652e-03],
        [ 3.31148366e-03, -1.59712532e-03, -6.98893055e-05, ...,
         -4.33085300e-03,  1.85002154e-03, -5.29798772e-03],
        ...,
        [-3.95849440e-03,  7.81338848e-03,  6.80229161e-03, ...,
         -1.95682910e-03, -1.15595162e-02, -8.90797656e-03],
        [-5.74252149e-03, -1.64745070e-04,  4.65748319e-03, ...,
         -1.02727041e-02, -4.12336364e-03, -1.05308602e-02],
        [-4.63347416e-03, -5.98690519e-03,  1.03861084e-02, ...,
         -1.09854760e-02, -1.75718020e-03, -2.37987866e-03]],

       [[-2.24520918e-03,  2.46209581e-03, -1.56388478e-03, ...,
         -3.19403992e-03, -5.13293501e-03,  4.70929965e-03],
        [-8.08521081e-03, -1.20279146e-03, -3.

In [36]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [37]:
sampled_indices

<tf.Tensor: shape=(200, 1), dtype=int64, numpy=
array([[100],
       [ 84],
       [ 90],
       [  8],
       [ 84],
       [ 69],
       [ 43],
       [ 25],
       [  4],
       [ 79],
       [ 31],
       [ 15],
       [ 18],
       [ 99],
       [ 61],
       [ 34],
       [ 94],
       [ 91],
       [ 76],
       [ 98],
       [ 39],
       [ 56],
       [ 83],
       [ 97],
       [ 36],
       [ 58],
       [101],
       [ 40],
       [ 53],
       [ 66],
       [  1],
       [  1],
       [ 42],
       [ 88],
       [ 25],
       [ 60],
       [ 78],
       [ 26],
       [ 94],
       [ 96],
       [ 29],
       [ 38],
       [ 31],
       [ 51],
       [  0],
       [ 70],
       [ 55],
       [ 95],
       [ 66],
       [ 46],
       [ 45],
       [101],
       [ 46],
       [ 72],
       [  4],
       [  8],
       [ 90],
       [ 94],
       [ 69],
       [ 69],
       [ 13],
       [ 91],
       [ 23],
       [ 24],
       [  3],
       [ 49],
       [  4],
       [ 28],


In [38]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [39]:
sampled_indices

array([100,  84,  90,   8,  84,  69,  43,  25,   4,  79,  31,  15,  18,
        99,  61,  34,  94,  91,  76,  98,  39,  56,  83,  97,  36,  58,
       101,  40,  53,  66,   1,   1,  42,  88,  25,  60,  78,  26,  94,
        96,  29,  38,  31,  51,   0,  70,  55,  95,  66,  46,  45, 101,
        46,  72,   4,   8,  90,  94,  69,  69,  13,  91,  23,  24,   3,
        49,   4,  28,  56,   0,  27,  41,  75,  63,  15,   5,   3,  93,
        97,  74,  12,  83,  42,  44,  99,  53,  82,  18,   3,  86,  99,
        78, 102,  92,  97,  12,  71,  92,  47,  59,  33,  12,  90,  11,
         2,  23,  62,   8,  38,  32,  10, 101,  86,  47,  49,   6,  70,
        68,  25,  38,  21,  37,   0,  90,  24,  88,  68,  87,  82,  86,
        70,  98,  30,  68,  28,  19,  83,  11,  67,  56,  70,  33,  33,
        60,  91,  42,  37,  43,  59,  10,  11,  78,  13,   4,   6,  82,
         1,  21,  41,  48,  78,  39,  69,  22,  18,  36,  58,  93,  45,
        91,  48,  52,  99,  49,  89,  39,  75,  22,  57,  31,  6

In [40]:
epochs = 30

In [41]:
model.fit(dataset,epochs=epochs)

Epoch 1/30
92/92 [==============================] - 29s 224ms/step - loss: 3.1807
Epoch 2/30
92/92 [==============================] - 25s 222ms/step - loss: 2.4135
Epoch 3/30
92/92 [==============================] - 25s 232ms/step - loss: 2.2217
Epoch 4/30
92/92 [==============================] - 25s 232ms/step - loss: 2.0363
Epoch 5/30
92/92 [==============================] - 25s 233ms/step - loss: 1.8692
Epoch 6/30
92/92 [==============================] - 25s 233ms/step - loss: 1.7267
Epoch 7/30
92/92 [==============================] - 24s 228ms/step - loss: 1.6112
Epoch 8/30
92/92 [==============================] - 26s 241ms/step - loss: 1.5237
Epoch 9/30
92/92 [==============================] - 25s 230ms/step - loss: 1.4587
Epoch 10/30
92/92 [==============================] - 25s 226ms/step - loss: 1.4082
Epoch 11/30
92/92 [==============================] - 25s 239ms/step - loss: 1.3692
Epoch 12/30
92/92 [==============================] - 25s 231ms/step - loss: 1.3353
Epoch 13/30
9

In [42]:
model.save('EM.Forst.h5')

In [43]:
from tensorflow.keras.models import load_model

In [44]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

model.load_weights('EM.Forst.h5')

model.build(tf.TensorShape([1, None]))


In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (1, None, 64)             6592      
                                                                 
 gru_1 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_1 (Dense)             (1, None, 103)            105781    
                                                                 
Total params: 3,473,549
Trainable params: 3,473,549
Non-trainable params: 0
_________________________________________________________________


In [46]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected

  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [51]:
print(generate_text(model,"When she was",gen_size=100))

When she was voice, and minded what he said to Mr. Honeychurch right—kindly, and to hear the funires
flood, the 
